/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIAccountChallenge;
import io.ownera.ledger.adapter.api.model.APINetworkAccountOperationErrorInformation;
import io.ownera.ledger.adapter.api.model.APINetworkAccountRecord;
import io.ownera.ledger.adapter.api.model.APIOperationMetadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Returned for &#x60;207&#x60; from &#x60;POST /accounts/create&#x60;. Structurally a superset of AccountOperationAccepted (the router decodes both create responses into this one type), adding the LA-issued challenge. 
 */
@JsonPropertyOrder({
  APIAccountOperationChallenge.JSON_PROPERTY_CID,
  APIAccountOperationChallenge.JSON_PROPERTY_IS_COMPLETED,
  APIAccountOperationChallenge.JSON_PROPERTY_OPERATION_METADATA,
  APIAccountOperationChallenge.JSON_PROPERTY_RESPONSE,
  APIAccountOperationChallenge.JSON_PROPERTY_ACCOUNTS,
  APIAccountOperationChallenge.JSON_PROPERTY_ERROR,
  APIAccountOperationChallenge.JSON_PROPERTY_EXPIRES_IN_SECONDS,
  APIAccountOperationChallenge.JSON_PROPERTY_CHALLENGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-14T17:39:52.798919559+03:00[Asia/Jerusalem]", comments = "Generator version: 7.6.0")
public class APIAccountOperationChallenge {
  public static final String JSON_PROPERTY_CID = "cid";
  private String cid;

  public static final String JSON_PROPERTY_IS_COMPLETED = "isCompleted";
  private Boolean isCompleted = false;

  public static final String JSON_PROPERTY_OPERATION_METADATA = "operationMetadata";
  private APIOperationMetadata operationMetadata;

  public static final String JSON_PROPERTY_RESPONSE = "response";
  private APINetworkAccountRecord response;

  public static final String JSON_PROPERTY_ACCOUNTS = "accounts";
  private List<APINetworkAccountRecord> accounts = new ArrayList<>();

  public static final String JSON_PROPERTY_ERROR = "error";
  private APINetworkAccountOperationErrorInformation error;

  public static final String JSON_PROPERTY_EXPIRES_IN_SECONDS = "expiresInSeconds";
  private Long expiresInSeconds;

  public static final String JSON_PROPERTY_CHALLENGE = "challenge";
  private APIAccountChallenge challenge;

  public APIAccountOperationChallenge() { 
  }

  public APIAccountOperationChallenge cid(String cid) {
    this.cid = cid;
    return this;
  }

   /**
   * unique correlation id which identify the operation
   * @return cid
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCid() {
    return cid;
  }


  @JsonProperty(JSON_PROPERTY_CID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCid(String cid) {
    this.cid = cid;
  }


  public APIAccountOperationChallenge isCompleted(Boolean isCompleted) {
    this.isCompleted = isCompleted;
    return this;
  }

   /**
   * flag indicating if the operation completed, if true then error or response must be present (but not both)
   * @return isCompleted
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_COMPLETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsCompleted() {
    return isCompleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_COMPLETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsCompleted(Boolean isCompleted) {
    this.isCompleted = isCompleted;
  }


  public APIAccountOperationChallenge operationMetadata(APIOperationMetadata operationMetadata) {
    this.operationMetadata = operationMetadata;
    return this;
  }

   /**
   * Get operationMetadata
   * @return operationMetadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATION_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public APIOperationMetadata getOperationMetadata() {
    return operationMetadata;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationMetadata(APIOperationMetadata operationMetadata) {
    this.operationMetadata = operationMetadata;
  }


  public APIAccountOperationChallenge response(APINetworkAccountRecord response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public APINetworkAccountRecord getResponse() {
    return response;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponse(APINetworkAccountRecord response) {
    this.response = response;
  }


  public APIAccountOperationChallenge accounts(List<APINetworkAccountRecord> accounts) {
    this.accounts = accounts;
    return this;
  }

  public APIAccountOperationChallenge addAccountsItem(APINetworkAccountRecord accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Lookup result (&#x60;POST /accounts/lookup&#x60;): every production account the LA holds for the investor on the asset — the router binds exactly this list. Present only for lookup operations — create/bind keep the singular &#x60;response&#x60;. Empty on a successful lookup that found nothing. 
   * @return accounts
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<APINetworkAccountRecord> getAccounts() {
    return accounts;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccounts(List<APINetworkAccountRecord> accounts) {
    this.accounts = accounts;
  }


  public APIAccountOperationChallenge error(APINetworkAccountOperationErrorInformation error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public APINetworkAccountOperationErrorInformation getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(APINetworkAccountOperationErrorInformation error) {
    this.error = error;
  }


  public APIAccountOperationChallenge expiresInSeconds(Long expiresInSeconds) {
    this.expiresInSeconds = expiresInSeconds;
    return this;
  }

   /**
   * Onboarding deadline the ledger adapter grants for this create/bind, in seconds from now. The asset node arms the workflow&#39;s whole-process timeout from this value (set once, at acceptance). Omitted/zero &#x3D;&gt; no auto-expiry. 
   * @return expiresInSeconds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_IN_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiresInSeconds() {
    return expiresInSeconds;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_IN_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresInSeconds(Long expiresInSeconds) {
    this.expiresInSeconds = expiresInSeconds;
  }


  public APIAccountOperationChallenge challenge(APIAccountChallenge challenge) {
    this.challenge = challenge;
    return this;
  }

   /**
   * Get challenge
   * @return challenge
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APIAccountChallenge getChallenge() {
    return challenge;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChallenge(APIAccountChallenge challenge) {
    this.challenge = challenge;
  }


  /**
   * Return true if this AccountOperationChallenge object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIAccountOperationChallenge accountOperationChallenge = (APIAccountOperationChallenge) o;
    return Objects.equals(this.cid, accountOperationChallenge.cid) &&
        Objects.equals(this.isCompleted, accountOperationChallenge.isCompleted) &&
        Objects.equals(this.operationMetadata, accountOperationChallenge.operationMetadata) &&
        Objects.equals(this.response, accountOperationChallenge.response) &&
        Objects.equals(this.accounts, accountOperationChallenge.accounts) &&
        Objects.equals(this.error, accountOperationChallenge.error) &&
        Objects.equals(this.expiresInSeconds, accountOperationChallenge.expiresInSeconds) &&
        Objects.equals(this.challenge, accountOperationChallenge.challenge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, isCompleted, operationMetadata, response, accounts, error, expiresInSeconds, challenge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIAccountOperationChallenge {\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    isCompleted: ").append(toIndentedString(isCompleted)).append("\n");
    sb.append("    operationMetadata: ").append(toIndentedString(operationMetadata)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    expiresInSeconds: ").append(toIndentedString(expiresInSeconds)).append("\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `cid` to the URL query string
    if (getCid() != null) {
      joiner.add(String.format("%scid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCid()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `isCompleted` to the URL query string
    if (getIsCompleted() != null) {
      joiner.add(String.format("%sisCompleted%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsCompleted()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `operationMetadata` to the URL query string
    if (getOperationMetadata() != null) {
      joiner.add(getOperationMetadata().toUrlQueryString(prefix + "operationMetadata" + suffix));
    }

    // add `response` to the URL query string
    if (getResponse() != null) {
      joiner.add(getResponse().toUrlQueryString(prefix + "response" + suffix));
    }

    // add `accounts` to the URL query string
    if (getAccounts() != null) {
      for (int i = 0; i < getAccounts().size(); i++) {
        if (getAccounts().get(i) != null) {
          joiner.add(getAccounts().get(i).toUrlQueryString(String.format("%saccounts%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    // add `expiresInSeconds` to the URL query string
    if (getExpiresInSeconds() != null) {
      joiner.add(String.format("%sexpiresInSeconds%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExpiresInSeconds()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `challenge` to the URL query string
    if (getChallenge() != null) {
      joiner.add(getChallenge().toUrlQueryString(prefix + "challenge" + suffix));
    }

    return joiner.toString();
  }
}

