/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIAsset;
import io.ownera.ledger.adapter.api.model.APIBalanceMarker;
import io.ownera.ledger.adapter.api.model.APIFinIdAccountBase;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * APIAssetBalanceInfoRequest
 */
@JsonPropertyOrder({
  APIAssetBalanceInfoRequest.JSON_PROPERTY_ACCOUNT,
  APIAssetBalanceInfoRequest.JSON_PROPERTY_ASSET,
  APIAssetBalanceInfoRequest.JSON_PROPERTY_MARKER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-23T16:47:06.183506981+03:00[Asia/Jerusalem]")
public class APIAssetBalanceInfoRequest {
  public static final String JSON_PROPERTY_ACCOUNT = "account";
  private APIFinIdAccountBase account;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private APIAsset asset;

  public static final String JSON_PROPERTY_MARKER = "marker";
  private APIBalanceMarker marker;

  public APIAssetBalanceInfoRequest() { 
  }

  public APIAssetBalanceInfoRequest account(APIFinIdAccountBase account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APIFinIdAccountBase getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccount(APIFinIdAccountBase account) {
    this.account = account;
  }


  public APIAssetBalanceInfoRequest asset(APIAsset asset) {
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APIAsset getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(APIAsset asset) {
    this.asset = asset;
  }


  public APIAssetBalanceInfoRequest marker(APIBalanceMarker marker) {
    this.marker = marker;
    return this;
  }

   /**
   * Get marker
   * @return marker
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public APIBalanceMarker getMarker() {
    return marker;
  }


  @JsonProperty(JSON_PROPERTY_MARKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarker(APIBalanceMarker marker) {
    this.marker = marker;
  }


  /**
   * Return true if this AssetBalanceInfoRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIAssetBalanceInfoRequest assetBalanceInfoRequest = (APIAssetBalanceInfoRequest) o;
    return Objects.equals(this.account, assetBalanceInfoRequest.account) &&
        Objects.equals(this.asset, assetBalanceInfoRequest.asset) &&
        Objects.equals(this.marker, assetBalanceInfoRequest.marker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, asset, marker);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIAssetBalanceInfoRequest {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    marker: ").append(toIndentedString(marker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `account` to the URL query string
    if (getAccount() != null) {
      joiner.add(getAccount().toUrlQueryString(prefix + "account" + suffix));
    }

    // add `asset` to the URL query string
    if (getAsset() != null) {
      joiner.add(getAsset().toUrlQueryString(prefix + "asset" + suffix));
    }

    // add `marker` to the URL query string
    if (getMarker() != null) {
      joiner.add(getMarker().toUrlQueryString(prefix + "marker" + suffix));
    }

    return joiner.toString();
  }
}

