/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIAccountOwnershipSignature;
import io.ownera.ledger.adapter.api.model.APINetworkAccount;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Bind-info block. When present in &#x60;CreateAccountRequest&#x60;, signals the bind-existing flow. 
 */
@JsonPropertyOrder({
  APIBindInfo.JSON_PROPERTY_NETWORK_ACCOUNT,
  APIBindInfo.JSON_PROPERTY_OWNERSHIP_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-14T17:39:52.798919559+03:00[Asia/Jerusalem]", comments = "Generator version: 7.6.0")
public class APIBindInfo {
  public static final String JSON_PROPERTY_NETWORK_ACCOUNT = "networkAccount";
  private APINetworkAccount networkAccount;

  public static final String JSON_PROPERTY_OWNERSHIP_SIGNATURE = "ownershipSignature";
  private APIAccountOwnershipSignature ownershipSignature;

  public APIBindInfo() { 
  }

  public APIBindInfo networkAccount(APINetworkAccount networkAccount) {
    this.networkAccount = networkAccount;
    return this;
  }

   /**
   * Get networkAccount
   * @return networkAccount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NETWORK_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APINetworkAccount getNetworkAccount() {
    return networkAccount;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetworkAccount(APINetworkAccount networkAccount) {
    this.networkAccount = networkAccount;
  }


  public APIBindInfo ownershipSignature(APIAccountOwnershipSignature ownershipSignature) {
    this.ownershipSignature = ownershipSignature;
    return this;
  }

   /**
   * Get ownershipSignature
   * @return ownershipSignature
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OWNERSHIP_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APIAccountOwnershipSignature getOwnershipSignature() {
    return ownershipSignature;
  }


  @JsonProperty(JSON_PROPERTY_OWNERSHIP_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwnershipSignature(APIAccountOwnershipSignature ownershipSignature) {
    this.ownershipSignature = ownershipSignature;
  }


  /**
   * Return true if this BindInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBindInfo bindInfo = (APIBindInfo) o;
    return Objects.equals(this.networkAccount, bindInfo.networkAccount) &&
        Objects.equals(this.ownershipSignature, bindInfo.ownershipSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkAccount, ownershipSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBindInfo {\n");
    sb.append("    networkAccount: ").append(toIndentedString(networkAccount)).append("\n");
    sb.append("    ownershipSignature: ").append(toIndentedString(ownershipSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `networkAccount` to the URL query string
    if (getNetworkAccount() != null) {
      joiner.add(getNetworkAccount().toUrlQueryString(prefix + "networkAccount" + suffix));
    }

    // add `ownershipSignature` to the URL query string
    if (getOwnershipSignature() != null) {
      joiner.add(getOwnershipSignature().toUrlQueryString(prefix + "ownershipSignature" + suffix));
    }

    return joiner.toString();
  }
}

