/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APICustomAsset;
import io.ownera.ledger.adapter.api.model.APIFinp2pAssetWithType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.ownera.ledger.adapter.api.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-23T16:47:06.183506981+03:00[Asia/Jerusalem]")
@JsonDeserialize(using = APIDepositAsset.APIDepositAssetDeserializer.class)
@JsonSerialize(using = APIDepositAsset.APIDepositAssetSerializer.class)
public class APIDepositAsset extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(APIDepositAsset.class.getName());

    public static class APIDepositAssetSerializer extends StdSerializer<APIDepositAsset> {
        public APIDepositAssetSerializer(Class<APIDepositAsset> t) {
            super(t);
        }

        public APIDepositAssetSerializer() {
            this(null);
        }

        @Override
        public void serialize(APIDepositAsset value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class APIDepositAssetDeserializer extends StdDeserializer<APIDepositAsset> {
        public APIDepositAssetDeserializer() {
            this(APIDepositAsset.class);
        }

        public APIDepositAssetDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public APIDepositAsset deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize APICustomAsset
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APICustomAsset.class.equals(Integer.class) || APICustomAsset.class.equals(Long.class) || APICustomAsset.class.equals(Float.class) || APICustomAsset.class.equals(Double.class) || APICustomAsset.class.equals(Boolean.class) || APICustomAsset.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APICustomAsset.class.equals(Integer.class) || APICustomAsset.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APICustomAsset.class.equals(Float.class) || APICustomAsset.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APICustomAsset.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APICustomAsset.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APICustomAsset.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APICustomAsset'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APICustomAsset'", e);
            }

            // deserialize APIFinp2pAssetWithType
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIFinp2pAssetWithType.class.equals(Integer.class) || APIFinp2pAssetWithType.class.equals(Long.class) || APIFinp2pAssetWithType.class.equals(Float.class) || APIFinp2pAssetWithType.class.equals(Double.class) || APIFinp2pAssetWithType.class.equals(Boolean.class) || APIFinp2pAssetWithType.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIFinp2pAssetWithType.class.equals(Integer.class) || APIFinp2pAssetWithType.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIFinp2pAssetWithType.class.equals(Float.class) || APIFinp2pAssetWithType.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIFinp2pAssetWithType.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIFinp2pAssetWithType.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIFinp2pAssetWithType.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIFinp2pAssetWithType'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIFinp2pAssetWithType'", e);
            }

            if (match == 1) {
                APIDepositAsset ret = new APIDepositAsset();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for APIDepositAsset: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public APIDepositAsset getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "APIDepositAsset cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public APIDepositAsset() {
        super("oneOf", Boolean.FALSE);
    }

    public APIDepositAsset(APICustomAsset o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public APIDepositAsset(APIFinp2pAssetWithType o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("APICustomAsset", APICustomAsset.class);
        schemas.put("APIFinp2pAssetWithType", APIFinp2pAssetWithType.class);
        JSON.registerDescendants(APIDepositAsset.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("custom", APICustomAsset.class);
        mappings.put("customAsset", APICustomAsset.class);
        mappings.put("finp2p", APIFinp2pAssetWithType.class);
        mappings.put("finp2pAssetWithType", APIFinp2pAssetWithType.class);
        mappings.put("depositAsset", APIDepositAsset.class);
        JSON.registerDiscriminator(APIDepositAsset.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return APIDepositAsset.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * APICustomAsset, APIFinp2pAssetWithType
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(APICustomAsset.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(APIFinp2pAssetWithType.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be APICustomAsset, APIFinp2pAssetWithType");
    }

    /**
     * Get the actual instance, which can be the following:
     * APICustomAsset, APIFinp2pAssetWithType
     *
     * @return The actual instance (APICustomAsset, APIFinp2pAssetWithType)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `APICustomAsset`. If the actual instance is not `APICustomAsset`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APICustomAsset`
     * @throws ClassCastException if the instance is not `APICustomAsset`
     */
    public APICustomAsset getAPICustomAsset() throws ClassCastException {
        return (APICustomAsset)super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIFinp2pAssetWithType`. If the actual instance is not `APIFinp2pAssetWithType`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIFinp2pAssetWithType`
     * @throws ClassCastException if the instance is not `APIFinp2pAssetWithType`
     */
    public APIFinp2pAssetWithType getAPIFinp2pAssetWithType() throws ClassCastException {
        return (APIFinp2pAssetWithType)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof APIFinp2pAssetWithType) {
        if (getActualInstance() != null) {
          joiner.add(((APIFinp2pAssetWithType)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof APICustomAsset) {
        if (getActualInstance() != null) {
          joiner.add(((APICustomAsset)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

