/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * APIExecutionPlanInstructionProposal
 */
@JsonPropertyOrder({
  APIExecutionPlanInstructionProposal.JSON_PROPERTY_PROPOSAL_TYPE,
  APIExecutionPlanInstructionProposal.JSON_PROPERTY_INSTRUCTION_SEQUENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-23T16:47:06.183506981+03:00[Asia/Jerusalem]")
public class APIExecutionPlanInstructionProposal {
  /**
   * Gets or Sets proposalType
   */
  public enum ProposalTypeEnum {
    INSTRUCTION("instruction");

    private String value;

    ProposalTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProposalTypeEnum fromValue(String value) {
      for (ProposalTypeEnum b : ProposalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROPOSAL_TYPE = "proposalType";
  private ProposalTypeEnum proposalType;

  public static final String JSON_PROPERTY_INSTRUCTION_SEQUENCE = "instructionSequence";
  private Integer instructionSequence;

  public APIExecutionPlanInstructionProposal() { 
  }

  public APIExecutionPlanInstructionProposal proposalType(ProposalTypeEnum proposalType) {
    this.proposalType = proposalType;
    return this;
  }

   /**
   * Get proposalType
   * @return proposalType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROPOSAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProposalTypeEnum getProposalType() {
    return proposalType;
  }


  @JsonProperty(JSON_PROPERTY_PROPOSAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposalType(ProposalTypeEnum proposalType) {
    this.proposalType = proposalType;
  }


  public APIExecutionPlanInstructionProposal instructionSequence(Integer instructionSequence) {
    this.instructionSequence = instructionSequence;
    return this;
  }

   /**
   * sequence number of the instruction completion event
   * minimum: 1
   * @return instructionSequence
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INSTRUCTION_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getInstructionSequence() {
    return instructionSequence;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUCTION_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstructionSequence(Integer instructionSequence) {
    this.instructionSequence = instructionSequence;
  }


  /**
   * Return true if this executionPlanInstructionProposal object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIExecutionPlanInstructionProposal executionPlanInstructionProposal = (APIExecutionPlanInstructionProposal) o;
    return Objects.equals(this.proposalType, executionPlanInstructionProposal.proposalType) &&
        Objects.equals(this.instructionSequence, executionPlanInstructionProposal.instructionSequence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proposalType, instructionSequence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIExecutionPlanInstructionProposal {\n");
    sb.append("    proposalType: ").append(toIndentedString(proposalType)).append("\n");
    sb.append("    instructionSequence: ").append(toIndentedString(instructionSequence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `proposalType` to the URL query string
    if (getProposalType() != null) {
      joiner.add(String.format("%sproposalType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProposalType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `instructionSequence` to the URL query string
    if (getInstructionSequence() != null) {
      joiner.add(String.format("%sinstructionSequence%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInstructionSequence()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

