/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIExecutionPlanCancellationProposal;
import io.ownera.ledger.adapter.api.model.APIExecutionPlanInstructionProposal;
import io.ownera.ledger.adapter.api.model.APIExecutionPlanResetProposal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.ownera.ledger.adapter.api.ApiClient;
import io.ownera.ledger.adapter.api.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T13:41:33.467077277+02:00[Asia/Jerusalem]", comments = "Generator version: 7.20.0")
@JsonDeserialize(using = APIExecutionPlanProposalRequestExecutionPlanProposal.APIExecutionPlanProposalRequestExecutionPlanProposalDeserializer.class)
@JsonSerialize(using = APIExecutionPlanProposalRequestExecutionPlanProposal.APIExecutionPlanProposalRequestExecutionPlanProposalSerializer.class)
public class APIExecutionPlanProposalRequestExecutionPlanProposal extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(APIExecutionPlanProposalRequestExecutionPlanProposal.class.getName());

    public static class APIExecutionPlanProposalRequestExecutionPlanProposalSerializer extends StdSerializer<APIExecutionPlanProposalRequestExecutionPlanProposal> {
        public APIExecutionPlanProposalRequestExecutionPlanProposalSerializer(Class<APIExecutionPlanProposalRequestExecutionPlanProposal> t) {
            super(t);
        }

        public APIExecutionPlanProposalRequestExecutionPlanProposalSerializer() {
            this(null);
        }

        @Override
        public void serialize(APIExecutionPlanProposalRequestExecutionPlanProposal value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class APIExecutionPlanProposalRequestExecutionPlanProposalDeserializer extends StdDeserializer<APIExecutionPlanProposalRequestExecutionPlanProposal> {
        public APIExecutionPlanProposalRequestExecutionPlanProposalDeserializer() {
            this(APIExecutionPlanProposalRequestExecutionPlanProposal.class);
        }

        public APIExecutionPlanProposalRequestExecutionPlanProposalDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public APIExecutionPlanProposalRequestExecutionPlanProposal deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize APIExecutionPlanCancellationProposal
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIExecutionPlanCancellationProposal.class.equals(Integer.class) || APIExecutionPlanCancellationProposal.class.equals(Long.class) || APIExecutionPlanCancellationProposal.class.equals(Float.class) || APIExecutionPlanCancellationProposal.class.equals(Double.class) || APIExecutionPlanCancellationProposal.class.equals(Boolean.class) || APIExecutionPlanCancellationProposal.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIExecutionPlanCancellationProposal.class.equals(Integer.class) || APIExecutionPlanCancellationProposal.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIExecutionPlanCancellationProposal.class.equals(Float.class) || APIExecutionPlanCancellationProposal.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIExecutionPlanCancellationProposal.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIExecutionPlanCancellationProposal.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIExecutionPlanCancellationProposal.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIExecutionPlanCancellationProposal'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIExecutionPlanCancellationProposal'", e);
            }

            // deserialize APIExecutionPlanInstructionProposal
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIExecutionPlanInstructionProposal.class.equals(Integer.class) || APIExecutionPlanInstructionProposal.class.equals(Long.class) || APIExecutionPlanInstructionProposal.class.equals(Float.class) || APIExecutionPlanInstructionProposal.class.equals(Double.class) || APIExecutionPlanInstructionProposal.class.equals(Boolean.class) || APIExecutionPlanInstructionProposal.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIExecutionPlanInstructionProposal.class.equals(Integer.class) || APIExecutionPlanInstructionProposal.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIExecutionPlanInstructionProposal.class.equals(Float.class) || APIExecutionPlanInstructionProposal.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIExecutionPlanInstructionProposal.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIExecutionPlanInstructionProposal.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIExecutionPlanInstructionProposal.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIExecutionPlanInstructionProposal'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIExecutionPlanInstructionProposal'", e);
            }

            // deserialize APIExecutionPlanResetProposal
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIExecutionPlanResetProposal.class.equals(Integer.class) || APIExecutionPlanResetProposal.class.equals(Long.class) || APIExecutionPlanResetProposal.class.equals(Float.class) || APIExecutionPlanResetProposal.class.equals(Double.class) || APIExecutionPlanResetProposal.class.equals(Boolean.class) || APIExecutionPlanResetProposal.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIExecutionPlanResetProposal.class.equals(Integer.class) || APIExecutionPlanResetProposal.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIExecutionPlanResetProposal.class.equals(Float.class) || APIExecutionPlanResetProposal.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIExecutionPlanResetProposal.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIExecutionPlanResetProposal.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIExecutionPlanResetProposal.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIExecutionPlanResetProposal'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIExecutionPlanResetProposal'", e);
            }

            if (match == 1) {
                APIExecutionPlanProposalRequestExecutionPlanProposal ret = new APIExecutionPlanProposalRequestExecutionPlanProposal();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for APIExecutionPlanProposalRequestExecutionPlanProposal: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public APIExecutionPlanProposalRequestExecutionPlanProposal getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "APIExecutionPlanProposalRequestExecutionPlanProposal cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public APIExecutionPlanProposalRequestExecutionPlanProposal() {
        super("oneOf", Boolean.FALSE);
    }

    public APIExecutionPlanProposalRequestExecutionPlanProposal(APIExecutionPlanCancellationProposal o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public APIExecutionPlanProposalRequestExecutionPlanProposal(APIExecutionPlanInstructionProposal o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public APIExecutionPlanProposalRequestExecutionPlanProposal(APIExecutionPlanResetProposal o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("APIExecutionPlanCancellationProposal", APIExecutionPlanCancellationProposal.class);
        schemas.put("APIExecutionPlanInstructionProposal", APIExecutionPlanInstructionProposal.class);
        schemas.put("APIExecutionPlanResetProposal", APIExecutionPlanResetProposal.class);
        JSON.registerDescendants(APIExecutionPlanProposalRequestExecutionPlanProposal.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("cancel", APIExecutionPlanCancellationProposal.class);
        mappings.put("instruction", APIExecutionPlanInstructionProposal.class);
        mappings.put("reset", APIExecutionPlanResetProposal.class);
        mappings.put("executionPlanProposalRequest_executionPlan_proposal", APIExecutionPlanProposalRequestExecutionPlanProposal.class);
        JSON.registerDiscriminator(APIExecutionPlanProposalRequestExecutionPlanProposal.class, "proposalType", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return APIExecutionPlanProposalRequestExecutionPlanProposal.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * APIExecutionPlanCancellationProposal, APIExecutionPlanInstructionProposal, APIExecutionPlanResetProposal
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(APIExecutionPlanCancellationProposal.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(APIExecutionPlanInstructionProposal.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(APIExecutionPlanResetProposal.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be APIExecutionPlanCancellationProposal, APIExecutionPlanInstructionProposal, APIExecutionPlanResetProposal");
    }

    /**
     * Get the actual instance, which can be the following:
     * APIExecutionPlanCancellationProposal, APIExecutionPlanInstructionProposal, APIExecutionPlanResetProposal
     *
     * @return The actual instance (APIExecutionPlanCancellationProposal, APIExecutionPlanInstructionProposal, APIExecutionPlanResetProposal)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIExecutionPlanCancellationProposal`. If the actual instance is not `APIExecutionPlanCancellationProposal`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIExecutionPlanCancellationProposal`
     * @throws ClassCastException if the instance is not `APIExecutionPlanCancellationProposal`
     */
    public APIExecutionPlanCancellationProposal getAPIExecutionPlanCancellationProposal() throws ClassCastException {
        return (APIExecutionPlanCancellationProposal)super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIExecutionPlanInstructionProposal`. If the actual instance is not `APIExecutionPlanInstructionProposal`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIExecutionPlanInstructionProposal`
     * @throws ClassCastException if the instance is not `APIExecutionPlanInstructionProposal`
     */
    public APIExecutionPlanInstructionProposal getAPIExecutionPlanInstructionProposal() throws ClassCastException {
        return (APIExecutionPlanInstructionProposal)super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIExecutionPlanResetProposal`. If the actual instance is not `APIExecutionPlanResetProposal`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIExecutionPlanResetProposal`
     * @throws ClassCastException if the instance is not `APIExecutionPlanResetProposal`
     */
    public APIExecutionPlanResetProposal getAPIExecutionPlanResetProposal() throws ClassCastException {
        return (APIExecutionPlanResetProposal)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof APIExecutionPlanCancellationProposal) {
        if (getActualInstance() != null) {
          joiner.add(((APIExecutionPlanCancellationProposal)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof APIExecutionPlanInstructionProposal) {
        if (getActualInstance() != null) {
          joiner.add(((APIExecutionPlanInstructionProposal)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof APIExecutionPlanResetProposal) {
        if (getActualInstance() != null) {
          joiner.add(((APIExecutionPlanResetProposal)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

