/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APILedgerAssetIdentifier;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * describes asset information
 */
@JsonPropertyOrder({
  APIFinp2pAsset.JSON_PROPERTY_ID,
  APIFinp2pAsset.JSON_PROPERTY_LEDGER_IDENTIFIER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-23T16:47:06.183506981+03:00[Asia/Jerusalem]")
public class APIFinp2pAsset {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LEDGER_IDENTIFIER = "ledgerIdentifier";
  private APILedgerAssetIdentifier ledgerIdentifier;

  public APIFinp2pAsset() { 
  }

  public APIFinp2pAsset id(String id) {
    this.id = id;
    return this;
  }

   /**
   * finp2p resource id format
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public APIFinp2pAsset ledgerIdentifier(APILedgerAssetIdentifier ledgerIdentifier) {
    this.ledgerIdentifier = ledgerIdentifier;
    return this;
  }

   /**
   * Get ledgerIdentifier
   * @return ledgerIdentifier
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LEDGER_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APILedgerAssetIdentifier getLedgerIdentifier() {
    return ledgerIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_LEDGER_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLedgerIdentifier(APILedgerAssetIdentifier ledgerIdentifier) {
    this.ledgerIdentifier = ledgerIdentifier;
  }


  /**
   * Return true if this finp2pAsset object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIFinp2pAsset finp2pAsset = (APIFinp2pAsset) o;
    return Objects.equals(this.id, finp2pAsset.id) &&
        Objects.equals(this.ledgerIdentifier, finp2pAsset.ledgerIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ledgerIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIFinp2pAsset {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ledgerIdentifier: ").append(toIndentedString(ledgerIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ledgerIdentifier` to the URL query string
    if (getLedgerIdentifier() != null) {
      joiner.add(getLedgerIdentifier().toUrlQueryString(prefix + "ledgerIdentifier" + suffix));
    }

    return joiner.toString();
  }
}

