/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIAccount;
import io.ownera.ledger.adapter.api.model.APIExecutionContext;
import io.ownera.ledger.adapter.api.model.APISignature;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * APITransferAssetRequest
 */
@JsonPropertyOrder({
  APITransferAssetRequest.JSON_PROPERTY_NONCE,
  APITransferAssetRequest.JSON_PROPERTY_SOURCE,
  APITransferAssetRequest.JSON_PROPERTY_DESTINATION,
  APITransferAssetRequest.JSON_PROPERTY_QUANTITY,
  APITransferAssetRequest.JSON_PROPERTY_SETTLEMENT_REF,
  APITransferAssetRequest.JSON_PROPERTY_SIGNATURE,
  APITransferAssetRequest.JSON_PROPERTY_EXECUTION_CONTEXT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-23T16:47:06.183506981+03:00[Asia/Jerusalem]")
public class APITransferAssetRequest {
  public static final String JSON_PROPERTY_NONCE = "nonce";
  private String nonce;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private APIAccount source;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  private APIAccount destination;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private String quantity;

  public static final String JSON_PROPERTY_SETTLEMENT_REF = "settlementRef";
  private String settlementRef;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private APISignature signature;

  public static final String JSON_PROPERTY_EXECUTION_CONTEXT = "executionContext";
  private APIExecutionContext executionContext;

  public APITransferAssetRequest() { 
  }

  public APITransferAssetRequest nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * 32 bytes buffer (24 randomly generated bytes by the client + 8 bytes epoch timestamp seconds) encoded to hex:    const nonce &#x3D; Buffer.alloc(32);   nonce.fill(crypto.randomBytes(24), 0, 24);    const nowEpochSeconds &#x3D; Math.floor(new Date().getTime() / 1000);   const t &#x3D; BigInt(nowEpochSeconds);   nonce.writeBigInt64BE(t, 24); 
   * @return nonce
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NONCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNonce() {
    return nonce;
  }


  @JsonProperty(JSON_PROPERTY_NONCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  public APITransferAssetRequest source(APIAccount source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APIAccount getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(APIAccount source) {
    this.source = source;
  }


  public APITransferAssetRequest destination(APIAccount destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APIAccount getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(APIAccount destination) {
    this.destination = destination;
  }


  public APITransferAssetRequest quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * How many units of the asset tokens
   * @return quantity
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  public APITransferAssetRequest settlementRef(String settlementRef) {
    this.settlementRef = settlementRef;
    return this;
  }

   /**
   * Reference to the corresponding payment operation
   * @return settlementRef
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSettlementRef() {
    return settlementRef;
  }


  @JsonProperty(JSON_PROPERTY_SETTLEMENT_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSettlementRef(String settlementRef) {
    this.settlementRef = settlementRef;
  }


  public APITransferAssetRequest signature(APISignature signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public APISignature getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(APISignature signature) {
    this.signature = signature;
  }


  public APITransferAssetRequest executionContext(APIExecutionContext executionContext) {
    this.executionContext = executionContext;
    return this;
  }

   /**
   * Get executionContext
   * @return executionContext
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTION_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public APIExecutionContext getExecutionContext() {
    return executionContext;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTION_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutionContext(APIExecutionContext executionContext) {
    this.executionContext = executionContext;
  }


  /**
   * Return true if this TransferAssetRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APITransferAssetRequest transferAssetRequest = (APITransferAssetRequest) o;
    return Objects.equals(this.nonce, transferAssetRequest.nonce) &&
        Objects.equals(this.source, transferAssetRequest.source) &&
        Objects.equals(this.destination, transferAssetRequest.destination) &&
        Objects.equals(this.quantity, transferAssetRequest.quantity) &&
        Objects.equals(this.settlementRef, transferAssetRequest.settlementRef) &&
        Objects.equals(this.signature, transferAssetRequest.signature) &&
        Objects.equals(this.executionContext, transferAssetRequest.executionContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonce, source, destination, quantity, settlementRef, signature, executionContext);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APITransferAssetRequest {\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    settlementRef: ").append(toIndentedString(settlementRef)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    executionContext: ").append(toIndentedString(executionContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `nonce` to the URL query string
    if (getNonce() != null) {
      joiner.add(String.format("%snonce%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNonce()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(getSource().toUrlQueryString(prefix + "source" + suffix));
    }

    // add `destination` to the URL query string
    if (getDestination() != null) {
      joiner.add(getDestination().toUrlQueryString(prefix + "destination" + suffix));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format("%squantity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQuantity()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `settlementRef` to the URL query string
    if (getSettlementRef() != null) {
      joiner.add(String.format("%ssettlementRef%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSettlementRef()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `signature` to the URL query string
    if (getSignature() != null) {
      joiner.add(getSignature().toUrlQueryString(prefix + "signature" + suffix));
    }

    // add `executionContext` to the URL query string
    if (getExecutionContext() != null) {
      joiner.add(getExecutionContext().toUrlQueryString(prefix + "executionContext" + suffix));
    }

    return joiner.toString();
  }
}

