/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIBalanceMarkerTimestamp;
import io.ownera.ledger.adapter.api.model.APIBalanceMarkerTransactionBlock;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.ownera.ledger.adapter.api.ApiClient;
import io.ownera.ledger.adapter.api.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-29T09:36:31.082697+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
@JsonDeserialize(using = APIBalanceMarker.APIBalanceMarkerDeserializer.class)
@JsonSerialize(using = APIBalanceMarker.APIBalanceMarkerSerializer.class)
public class APIBalanceMarker extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(APIBalanceMarker.class.getName());

    public static class APIBalanceMarkerSerializer extends StdSerializer<APIBalanceMarker> {
        public APIBalanceMarkerSerializer(Class<APIBalanceMarker> t) {
            super(t);
        }

        public APIBalanceMarkerSerializer() {
            this(null);
        }

        @Override
        public void serialize(APIBalanceMarker value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class APIBalanceMarkerDeserializer extends StdDeserializer<APIBalanceMarker> {
        public APIBalanceMarkerDeserializer() {
            this(APIBalanceMarker.class);
        }

        public APIBalanceMarkerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public APIBalanceMarker deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize APIBalanceMarkerTimestamp
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIBalanceMarkerTimestamp.class.equals(Integer.class) || APIBalanceMarkerTimestamp.class.equals(Long.class) || APIBalanceMarkerTimestamp.class.equals(Float.class) || APIBalanceMarkerTimestamp.class.equals(Double.class) || APIBalanceMarkerTimestamp.class.equals(Boolean.class) || APIBalanceMarkerTimestamp.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIBalanceMarkerTimestamp.class.equals(Integer.class) || APIBalanceMarkerTimestamp.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIBalanceMarkerTimestamp.class.equals(Float.class) || APIBalanceMarkerTimestamp.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIBalanceMarkerTimestamp.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIBalanceMarkerTimestamp.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIBalanceMarkerTimestamp.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIBalanceMarkerTimestamp'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIBalanceMarkerTimestamp'", e);
            }

            // deserialize APIBalanceMarkerTransactionBlock
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIBalanceMarkerTransactionBlock.class.equals(Integer.class) || APIBalanceMarkerTransactionBlock.class.equals(Long.class) || APIBalanceMarkerTransactionBlock.class.equals(Float.class) || APIBalanceMarkerTransactionBlock.class.equals(Double.class) || APIBalanceMarkerTransactionBlock.class.equals(Boolean.class) || APIBalanceMarkerTransactionBlock.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIBalanceMarkerTransactionBlock.class.equals(Integer.class) || APIBalanceMarkerTransactionBlock.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIBalanceMarkerTransactionBlock.class.equals(Float.class) || APIBalanceMarkerTransactionBlock.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIBalanceMarkerTransactionBlock.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIBalanceMarkerTransactionBlock.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIBalanceMarkerTransactionBlock.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIBalanceMarkerTransactionBlock'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIBalanceMarkerTransactionBlock'", e);
            }

            if (match == 1) {
                APIBalanceMarker ret = new APIBalanceMarker();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(Locale.ROOT, "Failed deserialization for APIBalanceMarker: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public APIBalanceMarker getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "APIBalanceMarker cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public APIBalanceMarker() {
        super("oneOf", Boolean.FALSE);
    }

    public APIBalanceMarker(APIBalanceMarkerTimestamp o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public APIBalanceMarker(APIBalanceMarkerTransactionBlock o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("APIBalanceMarkerTimestamp", APIBalanceMarkerTimestamp.class);
        schemas.put("APIBalanceMarkerTransactionBlock", APIBalanceMarkerTransactionBlock.class);
        JSON.registerDescendants(APIBalanceMarker.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("timestamp", APIBalanceMarkerTimestamp.class);
        mappings.put("transactionBlock", APIBalanceMarkerTransactionBlock.class);
        mappings.put("balanceMarker", APIBalanceMarker.class);
        JSON.registerDiscriminator(APIBalanceMarker.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return APIBalanceMarker.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * APIBalanceMarkerTimestamp, APIBalanceMarkerTransactionBlock
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(APIBalanceMarkerTimestamp.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(APIBalanceMarkerTransactionBlock.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be APIBalanceMarkerTimestamp, APIBalanceMarkerTransactionBlock");
    }

    /**
     * Get the actual instance, which can be the following:
     * APIBalanceMarkerTimestamp, APIBalanceMarkerTransactionBlock
     *
     * @return The actual instance (APIBalanceMarkerTimestamp, APIBalanceMarkerTransactionBlock)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIBalanceMarkerTimestamp`. If the actual instance is not `APIBalanceMarkerTimestamp`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIBalanceMarkerTimestamp`
     * @throws ClassCastException if the instance is not `APIBalanceMarkerTimestamp`
     */
    public APIBalanceMarkerTimestamp getAPIBalanceMarkerTimestamp() throws ClassCastException {
        return (APIBalanceMarkerTimestamp)super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIBalanceMarkerTransactionBlock`. If the actual instance is not `APIBalanceMarkerTransactionBlock`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIBalanceMarkerTransactionBlock`
     * @throws ClassCastException if the instance is not `APIBalanceMarkerTransactionBlock`
     */
    public APIBalanceMarkerTransactionBlock getAPIBalanceMarkerTransactionBlock() throws ClassCastException {
        return (APIBalanceMarkerTransactionBlock)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof APIBalanceMarkerTimestamp) {
        if (getActualInstance() != null) {
          joiner.add(((APIBalanceMarkerTimestamp)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof APIBalanceMarkerTransactionBlock) {
        if (getActualInstance() != null) {
          joiner.add(((APIBalanceMarkerTransactionBlock)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

