/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIEIP712Domain;
import io.ownera.ledger.adapter.api.model.APIEIP712Types;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * APIEIP712Template
 */
@JsonPropertyOrder({
  APIEIP712Template.JSON_PROPERTY_TYPE,
  APIEIP712Template.JSON_PROPERTY_DOMAIN,
  APIEIP712Template.JSON_PROPERTY_MESSAGE,
  APIEIP712Template.JSON_PROPERTY_TYPES,
  APIEIP712Template.JSON_PROPERTY_PRIMARY_TYPE,
  APIEIP712Template.JSON_PROPERTY_HASH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-29T09:36:31.082697+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
public class APIEIP712Template {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    EIP712(String.valueOf("EIP712"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nonnull
  private APIEIP712Domain domain;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private Object message;

  public static final String JSON_PROPERTY_TYPES = "types";
  @javax.annotation.Nonnull
  private APIEIP712Types types;

  public static final String JSON_PROPERTY_PRIMARY_TYPE = "primaryType";
  @javax.annotation.Nonnull
  private String primaryType;

  public static final String JSON_PROPERTY_HASH = "hash";
  @javax.annotation.Nonnull
  private String hash;

  public APIEIP712Template() { 
  }

  public APIEIP712Template type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public APIEIP712Template domain(@javax.annotation.Nonnull APIEIP712Domain domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public APIEIP712Domain getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(@javax.annotation.Nonnull APIEIP712Domain domain) {
    this.domain = domain;
  }


  public APIEIP712Template message(@javax.annotation.Nonnull Object message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Object getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull Object message) {
    this.message = message;
  }


  public APIEIP712Template types(@javax.annotation.Nonnull APIEIP712Types types) {
    this.types = types;
    return this;
  }

  /**
   * Get types
   * @return types
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public APIEIP712Types getTypes() {
    return types;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypes(@javax.annotation.Nonnull APIEIP712Types types) {
    this.types = types;
  }


  public APIEIP712Template primaryType(@javax.annotation.Nonnull String primaryType) {
    this.primaryType = primaryType;
    return this;
  }

  /**
   * Get primaryType
   * @return primaryType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRIMARY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPrimaryType() {
    return primaryType;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIMARY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrimaryType(@javax.annotation.Nonnull String primaryType) {
    this.primaryType = primaryType;
  }


  public APIEIP712Template hash(@javax.annotation.Nonnull String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * hex representation of template hash
   * @return hash
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HASH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHash() {
    return hash;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHash(@javax.annotation.Nonnull String hash) {
    this.hash = hash;
  }


  /**
   * Return true if this EIP712Template object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIEIP712Template eiP712Template = (APIEIP712Template) o;
    return Objects.equals(this.type, eiP712Template.type) &&
        Objects.equals(this.domain, eiP712Template.domain) &&
        Objects.equals(this.message, eiP712Template.message) &&
        Objects.equals(this.types, eiP712Template.types) &&
        Objects.equals(this.primaryType, eiP712Template.primaryType) &&
        Objects.equals(this.hash, eiP712Template.hash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, domain, message, types, primaryType, hash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIEIP712Template {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    primaryType: ").append(toIndentedString(primaryType)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(getDomain().toUrlQueryString(prefix + "domain" + suffix));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `types` to the URL query string
    if (getTypes() != null) {
      joiner.add(getTypes().toUrlQueryString(prefix + "types" + suffix));
    }

    // add `primaryType` to the URL query string
    if (getPrimaryType() != null) {
      joiner.add(String.format(Locale.ROOT, "%sprimaryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrimaryType()))));
    }

    // add `hash` to the URL query string
    if (getHash() != null) {
      joiner.add(String.format(Locale.ROOT, "%shash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHash()))));
    }

    return joiner.toString();
  }
}

