/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * APIFinP2PEVMOperatorDetails
 */
@JsonPropertyOrder({
  APIFinP2PEVMOperatorDetails.JSON_PROPERTY_FIN_P2_P_OPERATOR_CONTRACT_ADDRESS,
  APIFinP2PEVMOperatorDetails.JSON_PROPERTY_ALLOWANCE_REQUIRED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T10:24:19.848612+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
public class APIFinP2PEVMOperatorDetails {
  public static final String JSON_PROPERTY_FIN_P2_P_OPERATOR_CONTRACT_ADDRESS = "FinP2POperatorContractAddress";
  @javax.annotation.Nullable
  private String finP2POperatorContractAddress;

  public static final String JSON_PROPERTY_ALLOWANCE_REQUIRED = "allowanceRequired";
  @javax.annotation.Nullable
  private Boolean allowanceRequired;

  public APIFinP2PEVMOperatorDetails() { 
  }

  public APIFinP2PEVMOperatorDetails finP2POperatorContractAddress(@javax.annotation.Nullable String finP2POperatorContractAddress) {
    this.finP2POperatorContractAddress = finP2POperatorContractAddress;
    return this;
  }

  /**
   * The FinP2P Operator Contract Address
   * @return finP2POperatorContractAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIN_P2_P_OPERATOR_CONTRACT_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFinP2POperatorContractAddress() {
    return finP2POperatorContractAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_FIN_P2_P_OPERATOR_CONTRACT_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinP2POperatorContractAddress(@javax.annotation.Nullable String finP2POperatorContractAddress) {
    this.finP2POperatorContractAddress = finP2POperatorContractAddress;
  }


  public APIFinP2PEVMOperatorDetails allowanceRequired(@javax.annotation.Nullable Boolean allowanceRequired) {
    this.allowanceRequired = allowanceRequired;
    return this;
  }

  /**
   * Indicates if allowance is required
   * @return allowanceRequired
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOWANCE_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAllowanceRequired() {
    return allowanceRequired;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWANCE_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowanceRequired(@javax.annotation.Nullable Boolean allowanceRequired) {
    this.allowanceRequired = allowanceRequired;
  }


  /**
   * Return true if this finP2PEVMOperatorDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIFinP2PEVMOperatorDetails finP2PEVMOperatorDetails = (APIFinP2PEVMOperatorDetails) o;
    return Objects.equals(this.finP2POperatorContractAddress, finP2PEVMOperatorDetails.finP2POperatorContractAddress) &&
        Objects.equals(this.allowanceRequired, finP2PEVMOperatorDetails.allowanceRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(finP2POperatorContractAddress, allowanceRequired);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIFinP2PEVMOperatorDetails {\n");
    sb.append("    finP2POperatorContractAddress: ").append(toIndentedString(finP2POperatorContractAddress)).append("\n");
    sb.append("    allowanceRequired: ").append(toIndentedString(allowanceRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `FinP2POperatorContractAddress` to the URL query string
    if (getFinP2POperatorContractAddress() != null) {
      joiner.add(String.format(Locale.ROOT, "%sFinP2POperatorContractAddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFinP2POperatorContractAddress()))));
    }

    // add `allowanceRequired` to the URL query string
    if (getAllowanceRequired() != null) {
      joiner.add(String.format(Locale.ROOT, "%sallowanceRequired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAllowanceRequired()))));
    }

    return joiner.toString();
  }
}

