/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIField;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * APIHashGroup
 */
@JsonPropertyOrder({
  APIHashGroup.JSON_PROPERTY_HASH,
  APIHashGroup.JSON_PROPERTY_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-29T09:36:31.082697+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
public class APIHashGroup {
  public static final String JSON_PROPERTY_HASH = "hash";
  @javax.annotation.Nonnull
  private String hash;

  public static final String JSON_PROPERTY_FIELDS = "fields";
  @javax.annotation.Nonnull
  private List<APIField> fields = new ArrayList<>();

  public APIHashGroup() { 
  }

  public APIHashGroup hash(@javax.annotation.Nonnull String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * hex representation of the hash group hash value
   * @return hash
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HASH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHash() {
    return hash;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHash(@javax.annotation.Nonnull String hash) {
    this.hash = hash;
  }


  public APIHashGroup fields(@javax.annotation.Nonnull List<APIField> fields) {
    this.fields = fields;
    return this;
  }

  public APIHashGroup addFieldsItem(APIField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

  /**
   * list of fields by order they appear in the hash group
   * @return fields
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIELDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<APIField> getFields() {
    return fields;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFields(@javax.annotation.Nonnull List<APIField> fields) {
    this.fields = fields;
  }


  /**
   * Return true if this hashGroup object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIHashGroup hashGroup = (APIHashGroup) o;
    return Objects.equals(this.hash, hashGroup.hash) &&
        Objects.equals(this.fields, hashGroup.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, fields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIHashGroup {\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `hash` to the URL query string
    if (getHash() != null) {
      joiner.add(String.format(Locale.ROOT, "%shash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHash()))));
    }

    // add `fields` to the URL query string
    if (getFields() != null) {
      for (int i = 0; i < getFields().size(); i++) {
        if (getFields().get(i) != null) {
          joiner.add(getFields().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sfields%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

