/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIContractDetails;
import io.ownera.ledger.adapter.api.model.APILedgerTokenId;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * APILedgerAssetInfo
 */
@JsonPropertyOrder({
  APILedgerAssetInfo.JSON_PROPERTY_LEDGER_TOKEN_ID,
  APILedgerAssetInfo.JSON_PROPERTY_LEDGER_REFERENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-29T09:36:31.082697+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
public class APILedgerAssetInfo {
  public static final String JSON_PROPERTY_LEDGER_TOKEN_ID = "ledgerTokenId";
  @javax.annotation.Nonnull
  private APILedgerTokenId ledgerTokenId;

  public static final String JSON_PROPERTY_LEDGER_REFERENCE = "ledgerReference";
  @javax.annotation.Nullable
  private APIContractDetails ledgerReference;

  public APILedgerAssetInfo() { 
  }

  public APILedgerAssetInfo ledgerTokenId(@javax.annotation.Nonnull APILedgerTokenId ledgerTokenId) {
    this.ledgerTokenId = ledgerTokenId;
    return this;
  }

  /**
   * Get ledgerTokenId
   * @return ledgerTokenId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEDGER_TOKEN_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public APILedgerTokenId getLedgerTokenId() {
    return ledgerTokenId;
  }


  @JsonProperty(value = JSON_PROPERTY_LEDGER_TOKEN_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLedgerTokenId(@javax.annotation.Nonnull APILedgerTokenId ledgerTokenId) {
    this.ledgerTokenId = ledgerTokenId;
  }


  public APILedgerAssetInfo ledgerReference(@javax.annotation.Nullable APIContractDetails ledgerReference) {
    this.ledgerReference = ledgerReference;
    return this;
  }

  /**
   * Get ledgerReference
   * @return ledgerReference
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEDGER_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public APIContractDetails getLedgerReference() {
    return ledgerReference;
  }


  @JsonProperty(value = JSON_PROPERTY_LEDGER_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLedgerReference(@javax.annotation.Nullable APIContractDetails ledgerReference) {
    this.ledgerReference = ledgerReference;
  }


  /**
   * Return true if this ledgerAssetInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APILedgerAssetInfo ledgerAssetInfo = (APILedgerAssetInfo) o;
    return Objects.equals(this.ledgerTokenId, ledgerAssetInfo.ledgerTokenId) &&
        Objects.equals(this.ledgerReference, ledgerAssetInfo.ledgerReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ledgerTokenId, ledgerReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APILedgerAssetInfo {\n");
    sb.append("    ledgerTokenId: ").append(toIndentedString(ledgerTokenId)).append("\n");
    sb.append("    ledgerReference: ").append(toIndentedString(ledgerReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ledgerTokenId` to the URL query string
    if (getLedgerTokenId() != null) {
      joiner.add(getLedgerTokenId().toUrlQueryString(prefix + "ledgerTokenId" + suffix));
    }

    // add `ledgerReference` to the URL query string
    if (getLedgerReference() != null) {
      joiner.add(getLedgerReference().toUrlQueryString(prefix + "ledgerReference" + suffix));
    }

    return joiner.toString();
  }
}

