/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIRegulationError;
import io.ownera.ledger.adapter.api.model.APIRegulationFailure;
import io.ownera.ledger.adapter.api.model.APIValidationFailure;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.ownera.ledger.adapter.api.ApiClient;
import io.ownera.ledger.adapter.api.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T10:24:19.848612+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
@JsonDeserialize(using = APIPlanRejectedFailure.APIPlanRejectedFailureDeserializer.class)
@JsonSerialize(using = APIPlanRejectedFailure.APIPlanRejectedFailureSerializer.class)
public class APIPlanRejectedFailure extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(APIPlanRejectedFailure.class.getName());

    public static class APIPlanRejectedFailureSerializer extends StdSerializer<APIPlanRejectedFailure> {
        public APIPlanRejectedFailureSerializer(Class<APIPlanRejectedFailure> t) {
            super(t);
        }

        public APIPlanRejectedFailureSerializer() {
            this(null);
        }

        @Override
        public void serialize(APIPlanRejectedFailure value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class APIPlanRejectedFailureDeserializer extends StdDeserializer<APIPlanRejectedFailure> {
        public APIPlanRejectedFailureDeserializer() {
            this(APIPlanRejectedFailure.class);
        }

        public APIPlanRejectedFailureDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public APIPlanRejectedFailure deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize APIRegulationFailure
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIRegulationFailure.class.equals(Integer.class) || APIRegulationFailure.class.equals(Long.class) || APIRegulationFailure.class.equals(Float.class) || APIRegulationFailure.class.equals(Double.class) || APIRegulationFailure.class.equals(Boolean.class) || APIRegulationFailure.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIRegulationFailure.class.equals(Integer.class) || APIRegulationFailure.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIRegulationFailure.class.equals(Float.class) || APIRegulationFailure.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIRegulationFailure.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIRegulationFailure.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIRegulationFailure.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIRegulationFailure'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIRegulationFailure'", e);
            }

            // deserialize APIValidationFailure
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (APIValidationFailure.class.equals(Integer.class) || APIValidationFailure.class.equals(Long.class) || APIValidationFailure.class.equals(Float.class) || APIValidationFailure.class.equals(Double.class) || APIValidationFailure.class.equals(Boolean.class) || APIValidationFailure.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((APIValidationFailure.class.equals(Integer.class) || APIValidationFailure.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((APIValidationFailure.class.equals(Float.class) || APIValidationFailure.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (APIValidationFailure.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (APIValidationFailure.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(APIValidationFailure.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'APIValidationFailure'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'APIValidationFailure'", e);
            }

            if (match == 1) {
                APIPlanRejectedFailure ret = new APIPlanRejectedFailure();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(Locale.ROOT, "Failed deserialization for APIPlanRejectedFailure: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public APIPlanRejectedFailure getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "APIPlanRejectedFailure cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public APIPlanRejectedFailure() {
        super("oneOf", Boolean.FALSE);
    }

    public APIPlanRejectedFailure(APIRegulationFailure o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public APIPlanRejectedFailure(APIValidationFailure o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("APIRegulationFailure", APIRegulationFailure.class);
        schemas.put("APIValidationFailure", APIValidationFailure.class);
        JSON.registerDescendants(APIPlanRejectedFailure.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("regulationFailure", APIRegulationFailure.class);
        mappings.put("validationFailure", APIValidationFailure.class);
        mappings.put("PlanRejected_failure", APIPlanRejectedFailure.class);
        JSON.registerDiscriminator(APIPlanRejectedFailure.class, "failureType", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return APIPlanRejectedFailure.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * APIRegulationFailure, APIValidationFailure
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(APIRegulationFailure.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(APIValidationFailure.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be APIRegulationFailure, APIValidationFailure");
    }

    /**
     * Get the actual instance, which can be the following:
     * APIRegulationFailure, APIValidationFailure
     *
     * @return The actual instance (APIRegulationFailure, APIValidationFailure)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIRegulationFailure`. If the actual instance is not `APIRegulationFailure`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIRegulationFailure`
     * @throws ClassCastException if the instance is not `APIRegulationFailure`
     */
    public APIRegulationFailure getAPIRegulationFailure() throws ClassCastException {
        return (APIRegulationFailure)super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIValidationFailure`. If the actual instance is not `APIValidationFailure`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIValidationFailure`
     * @throws ClassCastException if the instance is not `APIValidationFailure`
     */
    public APIValidationFailure getAPIValidationFailure() throws ClassCastException {
        return (APIValidationFailure)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof APIValidationFailure) {
        if (getActualInstance() != null) {
          joiner.add(((APIValidationFailure)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof APIRegulationFailure) {
        if (getActualInstance() != null) {
          joiner.add(((APIRegulationFailure)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

