/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.APIAsset;
import io.ownera.ledger.adapter.api.model.APIExecutionContext;
import io.ownera.ledger.adapter.api.model.APISource;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * APIRollbackOperationRequest
 */
@JsonPropertyOrder({
  APIRollbackOperationRequest.JSON_PROPERTY_OPERATION_ID,
  APIRollbackOperationRequest.JSON_PROPERTY_SOURCE,
  APIRollbackOperationRequest.JSON_PROPERTY_QUANTITY,
  APIRollbackOperationRequest.JSON_PROPERTY_ASSET,
  APIRollbackOperationRequest.JSON_PROPERTY_EXECUTION_CONTEXT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T10:24:19.848612+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
public class APIRollbackOperationRequest {
  public static final String JSON_PROPERTY_OPERATION_ID = "operationId";
  @javax.annotation.Nonnull
  private String operationId;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @javax.annotation.Nonnull
  private APISource source;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nonnull
  private String quantity;

  public static final String JSON_PROPERTY_ASSET = "asset";
  @javax.annotation.Nonnull
  private APIAsset asset;

  public static final String JSON_PROPERTY_EXECUTION_CONTEXT = "executionContext";
  @javax.annotation.Nullable
  private APIExecutionContext executionContext;

  public APIRollbackOperationRequest() { 
  }

  public APIRollbackOperationRequest operationId(@javax.annotation.Nonnull String operationId) {
    this.operationId = operationId;
    return this;
  }

  /**
   * Hold operation id
   * @return operationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPERATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOperationId() {
    return operationId;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperationId(@javax.annotation.Nonnull String operationId) {
    this.operationId = operationId;
  }


  public APIRollbackOperationRequest source(@javax.annotation.Nonnull APISource source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public APISource getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@javax.annotation.Nonnull APISource source) {
    this.source = source;
  }


  public APIRollbackOperationRequest quantity(@javax.annotation.Nonnull String quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * How many units of the asset tokens
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(@javax.annotation.Nonnull String quantity) {
    this.quantity = quantity;
  }


  public APIRollbackOperationRequest asset(@javax.annotation.Nonnull APIAsset asset) {
    this.asset = asset;
    return this;
  }

  /**
   * Get asset
   * @return asset
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ASSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public APIAsset getAsset() {
    return asset;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(@javax.annotation.Nonnull APIAsset asset) {
    this.asset = asset;
  }


  public APIRollbackOperationRequest executionContext(@javax.annotation.Nullable APIExecutionContext executionContext) {
    this.executionContext = executionContext;
    return this;
  }

  /**
   * Get executionContext
   * @return executionContext
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXECUTION_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public APIExecutionContext getExecutionContext() {
    return executionContext;
  }


  @JsonProperty(value = JSON_PROPERTY_EXECUTION_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutionContext(@javax.annotation.Nullable APIExecutionContext executionContext) {
    this.executionContext = executionContext;
  }


  /**
   * Return true if this RollbackOperationRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIRollbackOperationRequest rollbackOperationRequest = (APIRollbackOperationRequest) o;
    return Objects.equals(this.operationId, rollbackOperationRequest.operationId) &&
        Objects.equals(this.source, rollbackOperationRequest.source) &&
        Objects.equals(this.quantity, rollbackOperationRequest.quantity) &&
        Objects.equals(this.asset, rollbackOperationRequest.asset) &&
        Objects.equals(this.executionContext, rollbackOperationRequest.executionContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationId, source, quantity, asset, executionContext);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIRollbackOperationRequest {\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    executionContext: ").append(toIndentedString(executionContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `operationId` to the URL query string
    if (getOperationId() != null) {
      joiner.add(String.format(Locale.ROOT, "%soperationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperationId()))));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(getSource().toUrlQueryString(prefix + "source" + suffix));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format(Locale.ROOT, "%squantity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuantity()))));
    }

    // add `asset` to the URL query string
    if (getAsset() != null) {
      joiner.add(getAsset().toUrlQueryString(prefix + "asset" + suffix));
    }

    // add `executionContext` to the URL query string
    if (getExecutionContext() != null) {
      joiner.add(getExecutionContext().toUrlQueryString(prefix + "executionContext" + suffix));
    }

    return joiner.toString();
  }
}

