/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P node will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.FinP2PEVMOperatorDetails;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * ContractDetails
 */
@JsonPropertyOrder({
  ContractDetails.JSON_PROPERTY_TYPE,
  ContractDetails.JSON_PROPERTY_NETWORK,
  ContractDetails.JSON_PROPERTY_ADDRESS,
  ContractDetails.JSON_PROPERTY_TOKEN_STANDARD,
  ContractDetails.JSON_PROPERTY_ADDITIONAL_CONTRACT_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-23T11:29:49.092442+03:00[Asia/Jerusalem]", comments = "Generator version: 7.9.0")
public class ContractDetails {
  /**
   * the type of the identifier
   */
  public enum TypeEnum {
    CONTRACT_DETAILS("contractDetails");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_NETWORK = "network";
  private String network;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_TOKEN_STANDARD = "TokenStandard";
  private String tokenStandard;

  public static final String JSON_PROPERTY_ADDITIONAL_CONTRACT_DETAILS = "additionalContractDetails";
  private FinP2PEVMOperatorDetails additionalContractDetails;

  public ContractDetails() { 
  }

  public ContractDetails type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * the type of the identifier
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public ContractDetails network(String network) {
    this.network = network;
    return this;
  }

  /**
   * the network
   * @return network
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(String network) {
    this.network = network;
  }


  public ContractDetails address(String address) {
    this.address = address;
    return this;
  }

  /**
   * the address
   * @return address
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(String address) {
    this.address = address;
  }


  public ContractDetails tokenStandard(String tokenStandard) {
    this.tokenStandard = tokenStandard;
    return this;
  }

  /**
   * The standard of the token (e.g., ERC20, ERC721)
   * @return tokenStandard
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_STANDARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTokenStandard() {
    return tokenStandard;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_STANDARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenStandard(String tokenStandard) {
    this.tokenStandard = tokenStandard;
  }


  public ContractDetails additionalContractDetails(FinP2PEVMOperatorDetails additionalContractDetails) {
    this.additionalContractDetails = additionalContractDetails;
    return this;
  }

  /**
   * Get additionalContractDetails
   * @return additionalContractDetails
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_CONTRACT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FinP2PEVMOperatorDetails getAdditionalContractDetails() {
    return additionalContractDetails;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_CONTRACT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalContractDetails(FinP2PEVMOperatorDetails additionalContractDetails) {
    this.additionalContractDetails = additionalContractDetails;
  }


  /**
   * Return true if this contractDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractDetails contractDetails = (ContractDetails) o;
    return Objects.equals(this.type, contractDetails.type) &&
        Objects.equals(this.network, contractDetails.network) &&
        Objects.equals(this.address, contractDetails.address) &&
        Objects.equals(this.tokenStandard, contractDetails.tokenStandard) &&
        Objects.equals(this.additionalContractDetails, contractDetails.additionalContractDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, network, address, tokenStandard, additionalContractDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractDetails {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    tokenStandard: ").append(toIndentedString(tokenStandard)).append("\n");
    sb.append("    additionalContractDetails: ").append(toIndentedString(additionalContractDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `network` to the URL query string
    if (getNetwork() != null) {
      joiner.add(String.format("%snetwork%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNetwork()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format("%saddress%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddress()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `TokenStandard` to the URL query string
    if (getTokenStandard() != null) {
      joiner.add(String.format("%sTokenStandard%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTokenStandard()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `additionalContractDetails` to the URL query string
    if (getAdditionalContractDetails() != null) {
      joiner.add(getAdditionalContractDetails().toUrlQueryString(prefix + "additionalContractDetails" + suffix));
    }

    return joiner.toString();
  }
}

