/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P node will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.CryptoWalletAccount;
import io.ownera.ledger.adapter.api.model.FiatAccount;
import io.ownera.ledger.adapter.api.model.FinIdAccount;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.ownera.ledger.adapter.api.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-23T11:29:49.092442+03:00[Asia/Jerusalem]", comments = "Generator version: 7.9.0")
@JsonDeserialize(using = DestinationAccount.DestinationAccountDeserializer.class)
@JsonSerialize(using = DestinationAccount.DestinationAccountSerializer.class)
public class DestinationAccount extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DestinationAccount.class.getName());

    public static class DestinationAccountSerializer extends StdSerializer<DestinationAccount> {
        public DestinationAccountSerializer(Class<DestinationAccount> t) {
            super(t);
        }

        public DestinationAccountSerializer() {
            this(null);
        }

        @Override
        public void serialize(DestinationAccount value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class DestinationAccountDeserializer extends StdDeserializer<DestinationAccount> {
        public DestinationAccountDeserializer() {
            this(DestinationAccount.class);
        }

        public DestinationAccountDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public DestinationAccount deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize CryptoWalletAccount
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CryptoWalletAccount.class.equals(Integer.class) || CryptoWalletAccount.class.equals(Long.class) || CryptoWalletAccount.class.equals(Float.class) || CryptoWalletAccount.class.equals(Double.class) || CryptoWalletAccount.class.equals(Boolean.class) || CryptoWalletAccount.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CryptoWalletAccount.class.equals(Integer.class) || CryptoWalletAccount.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CryptoWalletAccount.class.equals(Float.class) || CryptoWalletAccount.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CryptoWalletAccount.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CryptoWalletAccount.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CryptoWalletAccount.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CryptoWalletAccount'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CryptoWalletAccount'", e);
            }

            // deserialize FiatAccount
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (FiatAccount.class.equals(Integer.class) || FiatAccount.class.equals(Long.class) || FiatAccount.class.equals(Float.class) || FiatAccount.class.equals(Double.class) || FiatAccount.class.equals(Boolean.class) || FiatAccount.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((FiatAccount.class.equals(Integer.class) || FiatAccount.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((FiatAccount.class.equals(Float.class) || FiatAccount.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (FiatAccount.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (FiatAccount.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(FiatAccount.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'FiatAccount'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'FiatAccount'", e);
            }

            // deserialize FinIdAccount
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (FinIdAccount.class.equals(Integer.class) || FinIdAccount.class.equals(Long.class) || FinIdAccount.class.equals(Float.class) || FinIdAccount.class.equals(Double.class) || FinIdAccount.class.equals(Boolean.class) || FinIdAccount.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((FinIdAccount.class.equals(Integer.class) || FinIdAccount.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((FinIdAccount.class.equals(Float.class) || FinIdAccount.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (FinIdAccount.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (FinIdAccount.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(FinIdAccount.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'FinIdAccount'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'FinIdAccount'", e);
            }

            if (match == 1) {
                DestinationAccount ret = new DestinationAccount();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for DestinationAccount: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public DestinationAccount getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "DestinationAccount cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public DestinationAccount() {
        super("oneOf", Boolean.FALSE);
    }

    public DestinationAccount(CryptoWalletAccount o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public DestinationAccount(FiatAccount o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public DestinationAccount(FinIdAccount o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CryptoWalletAccount", CryptoWalletAccount.class);
        schemas.put("FiatAccount", FiatAccount.class);
        schemas.put("FinIdAccount", FinIdAccount.class);
        JSON.registerDescendants(DestinationAccount.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("cryptoWallet", CryptoWalletAccount.class);
        mappings.put("fiatAccount", FiatAccount.class);
        mappings.put("finId", FinIdAccount.class);
        mappings.put("cryptoWalletAccount", CryptoWalletAccount.class);
        mappings.put("finIdAccount", FinIdAccount.class);
        mappings.put("destination_account", DestinationAccount.class);
        JSON.registerDiscriminator(DestinationAccount.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DestinationAccount.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CryptoWalletAccount, FiatAccount, FinIdAccount
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(CryptoWalletAccount.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(FiatAccount.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(FinIdAccount.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CryptoWalletAccount, FiatAccount, FinIdAccount");
    }

    /**
     * Get the actual instance, which can be the following:
     * CryptoWalletAccount, FiatAccount, FinIdAccount
     *
     * @return The actual instance (CryptoWalletAccount, FiatAccount, FinIdAccount)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CryptoWalletAccount`. If the actual instance is not `CryptoWalletAccount`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CryptoWalletAccount`
     * @throws ClassCastException if the instance is not `CryptoWalletAccount`
     */
    public CryptoWalletAccount getCryptoWalletAccount() throws ClassCastException {
        return (CryptoWalletAccount)super.getActualInstance();
    }

    /**
     * Get the actual instance of `FiatAccount`. If the actual instance is not `FiatAccount`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `FiatAccount`
     * @throws ClassCastException if the instance is not `FiatAccount`
     */
    public FiatAccount getFiatAccount() throws ClassCastException {
        return (FiatAccount)super.getActualInstance();
    }

    /**
     * Get the actual instance of `FinIdAccount`. If the actual instance is not `FinIdAccount`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `FinIdAccount`
     * @throws ClassCastException if the instance is not `FinIdAccount`
     */
    public FinIdAccount getFinIdAccount() throws ClassCastException {
        return (FinIdAccount)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof FinIdAccount) {
        if (getActualInstance() != null) {
          joiner.add(((FinIdAccount)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof CryptoWalletAccount) {
        if (getActualInstance() != null) {
          joiner.add(((CryptoWalletAccount)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof FiatAccount) {
        if (getActualInstance() != null) {
          joiner.add(((FiatAccount)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

