/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P node will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.ExecutionContext;
import io.ownera.ledger.adapter.api.model.FinIdAccount;
import io.ownera.ledger.adapter.api.model.Finp2pAsset;
import io.ownera.ledger.adapter.api.model.Signature;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * IssueAssetsRequest
 */
@JsonPropertyOrder({
  IssueAssetsRequest.JSON_PROPERTY_NONCE,
  IssueAssetsRequest.JSON_PROPERTY_DESTINATION,
  IssueAssetsRequest.JSON_PROPERTY_QUANTITY,
  IssueAssetsRequest.JSON_PROPERTY_ASSET,
  IssueAssetsRequest.JSON_PROPERTY_SETTLEMENT_REF,
  IssueAssetsRequest.JSON_PROPERTY_SIGNATURE,
  IssueAssetsRequest.JSON_PROPERTY_EXECUTION_CONTEXT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-23T11:29:49.092442+03:00[Asia/Jerusalem]", comments = "Generator version: 7.9.0")
public class IssueAssetsRequest {
  public static final String JSON_PROPERTY_NONCE = "nonce";
  private String nonce;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  private FinIdAccount destination;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private String quantity;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private Finp2pAsset asset;

  public static final String JSON_PROPERTY_SETTLEMENT_REF = "settlementRef";
  private String settlementRef;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private Signature signature;

  public static final String JSON_PROPERTY_EXECUTION_CONTEXT = "executionContext";
  private ExecutionContext executionContext;

  public IssueAssetsRequest() { 
  }

  public IssueAssetsRequest nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

  /**
   * 32 bytes buffer (24 randomly generated bytes by the client + 8 bytes epoch timestamp seconds) encoded to hex:    const nonce &#x3D; Buffer.alloc(32);   nonce.fill(crypto.randomBytes(24), 0, 24);    const nowEpochSeconds &#x3D; Math.floor(new Date().getTime() / 1000);   const t &#x3D; BigInt(nowEpochSeconds);   nonce.writeBigInt64BE(t, 24); 
   * @return nonce
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NONCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNonce() {
    return nonce;
  }


  @JsonProperty(JSON_PROPERTY_NONCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  public IssueAssetsRequest destination(FinIdAccount destination) {
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FinIdAccount getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(FinIdAccount destination) {
    this.destination = destination;
  }


  public IssueAssetsRequest quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * How many units of the asset tokens
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  public IssueAssetsRequest asset(Finp2pAsset asset) {
    this.asset = asset;
    return this;
  }

  /**
   * Get asset
   * @return asset
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Finp2pAsset getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(Finp2pAsset asset) {
    this.asset = asset;
  }


  public IssueAssetsRequest settlementRef(String settlementRef) {
    this.settlementRef = settlementRef;
    return this;
  }

  /**
   * Reference to the corresponding settlement operation
   * @return settlementRef
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSettlementRef() {
    return settlementRef;
  }


  @JsonProperty(JSON_PROPERTY_SETTLEMENT_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSettlementRef(String settlementRef) {
    this.settlementRef = settlementRef;
  }


  public IssueAssetsRequest signature(Signature signature) {
    this.signature = signature;
    return this;
  }

  /**
   * Get signature
   * @return signature
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Signature getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(Signature signature) {
    this.signature = signature;
  }


  public IssueAssetsRequest executionContext(ExecutionContext executionContext) {
    this.executionContext = executionContext;
    return this;
  }

  /**
   * Get executionContext
   * @return executionContext
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTION_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ExecutionContext getExecutionContext() {
    return executionContext;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTION_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutionContext(ExecutionContext executionContext) {
    this.executionContext = executionContext;
  }


  /**
   * Return true if this IssueAssetsRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueAssetsRequest issueAssetsRequest = (IssueAssetsRequest) o;
    return Objects.equals(this.nonce, issueAssetsRequest.nonce) &&
        Objects.equals(this.destination, issueAssetsRequest.destination) &&
        Objects.equals(this.quantity, issueAssetsRequest.quantity) &&
        Objects.equals(this.asset, issueAssetsRequest.asset) &&
        Objects.equals(this.settlementRef, issueAssetsRequest.settlementRef) &&
        Objects.equals(this.signature, issueAssetsRequest.signature) &&
        Objects.equals(this.executionContext, issueAssetsRequest.executionContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonce, destination, quantity, asset, settlementRef, signature, executionContext);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueAssetsRequest {\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    settlementRef: ").append(toIndentedString(settlementRef)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    executionContext: ").append(toIndentedString(executionContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `nonce` to the URL query string
    if (getNonce() != null) {
      joiner.add(String.format("%snonce%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNonce()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `destination` to the URL query string
    if (getDestination() != null) {
      joiner.add(getDestination().toUrlQueryString(prefix + "destination" + suffix));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format("%squantity%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getQuantity()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `asset` to the URL query string
    if (getAsset() != null) {
      joiner.add(getAsset().toUrlQueryString(prefix + "asset" + suffix));
    }

    // add `settlementRef` to the URL query string
    if (getSettlementRef() != null) {
      joiner.add(String.format("%ssettlementRef%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSettlementRef()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `signature` to the URL query string
    if (getSignature() != null) {
      joiner.add(getSignature().toUrlQueryString(prefix + "signature" + suffix));
    }

    // add `executionContext` to the URL query string
    if (getExecutionContext() != null) {
      joiner.add(getExecutionContext().toUrlQueryString(prefix + "executionContext" + suffix));
    }

    return joiner.toString();
  }
}

