/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P node will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * RegulationError
 */
@JsonPropertyOrder({
  RegulationError.JSON_PROPERTY_REGULATION_TYPE,
  RegulationError.JSON_PROPERTY_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-23T11:29:49.092442+03:00[Asia/Jerusalem]", comments = "Generator version: 7.9.0")
public class RegulationError {
  public static final String JSON_PROPERTY_REGULATION_TYPE = "regulationType";
  private String regulationType;

  public static final String JSON_PROPERTY_DETAILS = "details";
  private String details;

  public RegulationError() { 
  }

  public RegulationError regulationType(String regulationType) {
    this.regulationType = regulationType;
    return this;
  }

  /**
   * the type of regulation
   * @return regulationType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REGULATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRegulationType() {
    return regulationType;
  }


  @JsonProperty(JSON_PROPERTY_REGULATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegulationType(String regulationType) {
    this.regulationType = regulationType;
  }


  public RegulationError details(String details) {
    this.details = details;
    return this;
  }

  /**
   * actionable details of the error
   * @return details
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDetails() {
    return details;
  }


  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetails(String details) {
    this.details = details;
  }


  /**
   * Return true if this RegulationError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegulationError regulationError = (RegulationError) o;
    return Objects.equals(this.regulationType, regulationError.regulationType) &&
        Objects.equals(this.details, regulationError.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regulationType, details);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegulationError {\n");
    sb.append("    regulationType: ").append(toIndentedString(regulationType)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `regulationType` to the URL query string
    if (getRegulationType() != null) {
      joiner.add(String.format("%sregulationType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRegulationType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `details` to the URL query string
    if (getDetails() != null) {
      joiner.add(String.format("%sdetails%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDetails()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

