/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P Router will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.OperationMetadata;
import io.ownera.ledger.adapter.api.model.Receipt;
import io.ownera.ledger.adapter.api.model.ReceiptOperationErrorInformation;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * RollbackOperationResponse
 */
@JsonPropertyOrder({
  RollbackOperationResponse.JSON_PROPERTY_CID,
  RollbackOperationResponse.JSON_PROPERTY_IS_COMPLETED,
  RollbackOperationResponse.JSON_PROPERTY_OPERATION_METADATA,
  RollbackOperationResponse.JSON_PROPERTY_ERROR,
  RollbackOperationResponse.JSON_PROPERTY_RESPONSE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-27T09:27:05.154160+02:00[Asia/Jerusalem]", comments = "Generator version: 7.16.0")
public class RollbackOperationResponse {
  public static final String JSON_PROPERTY_CID = "cid";
  @javax.annotation.Nonnull
  private String cid;

  public static final String JSON_PROPERTY_IS_COMPLETED = "isCompleted";
  @javax.annotation.Nonnull
  private Boolean isCompleted = false;

  public static final String JSON_PROPERTY_OPERATION_METADATA = "operationMetadata";
  @javax.annotation.Nullable
  private OperationMetadata operationMetadata;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private ReceiptOperationErrorInformation error;

  public static final String JSON_PROPERTY_RESPONSE = "response";
  @javax.annotation.Nullable
  private Receipt response;

  public RollbackOperationResponse() { 
  }

  public RollbackOperationResponse cid(@javax.annotation.Nonnull String cid) {
    this.cid = cid;
    return this;
  }

  /**
   * unique correlation id which identify the operation
   * @return cid
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCid() {
    return cid;
  }


  @JsonProperty(value = JSON_PROPERTY_CID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCid(@javax.annotation.Nonnull String cid) {
    this.cid = cid;
  }


  public RollbackOperationResponse isCompleted(@javax.annotation.Nonnull Boolean isCompleted) {
    this.isCompleted = isCompleted;
    return this;
  }

  /**
   * flag indicating if the operation completed, if true then error or response must be present (but not both)
   * @return isCompleted
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_COMPLETED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsCompleted() {
    return isCompleted;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_COMPLETED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsCompleted(@javax.annotation.Nonnull Boolean isCompleted) {
    this.isCompleted = isCompleted;
  }


  public RollbackOperationResponse operationMetadata(@javax.annotation.Nullable OperationMetadata operationMetadata) {
    this.operationMetadata = operationMetadata;
    return this;
  }

  /**
   * Get operationMetadata
   * @return operationMetadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATION_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OperationMetadata getOperationMetadata() {
    return operationMetadata;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationMetadata(@javax.annotation.Nullable OperationMetadata operationMetadata) {
    this.operationMetadata = operationMetadata;
  }


  public RollbackOperationResponse error(@javax.annotation.Nullable ReceiptOperationErrorInformation error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ReceiptOperationErrorInformation getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable ReceiptOperationErrorInformation error) {
    this.error = error;
  }


  public RollbackOperationResponse response(@javax.annotation.Nullable Receipt response) {
    this.response = response;
    return this;
  }

  /**
   * Get response
   * @return response
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Receipt getResponse() {
    return response;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponse(@javax.annotation.Nullable Receipt response) {
    this.response = response;
  }


  /**
   * Return true if this RollbackOperationResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RollbackOperationResponse rollbackOperationResponse = (RollbackOperationResponse) o;
    return Objects.equals(this.cid, rollbackOperationResponse.cid) &&
        Objects.equals(this.isCompleted, rollbackOperationResponse.isCompleted) &&
        Objects.equals(this.operationMetadata, rollbackOperationResponse.operationMetadata) &&
        Objects.equals(this.error, rollbackOperationResponse.error) &&
        Objects.equals(this.response, rollbackOperationResponse.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, isCompleted, operationMetadata, error, response);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RollbackOperationResponse {\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    isCompleted: ").append(toIndentedString(isCompleted)).append("\n");
    sb.append("    operationMetadata: ").append(toIndentedString(operationMetadata)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `cid` to the URL query string
    if (getCid() != null) {
      joiner.add(String.format(Locale.ROOT, "%scid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCid()))));
    }

    // add `isCompleted` to the URL query string
    if (getIsCompleted() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisCompleted%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsCompleted()))));
    }

    // add `operationMetadata` to the URL query string
    if (getOperationMetadata() != null) {
      joiner.add(getOperationMetadata().toUrlQueryString(prefix + "operationMetadata" + suffix));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    // add `response` to the URL query string
    if (getResponse() != null) {
      joiner.add(getResponse().toUrlQueryString(prefix + "response" + suffix));
    }

    return joiner.toString();
  }
}

