/*
 * Ledger Adapter Specification
 * This is the API specification for the Ledger Adapter with whom the FinP2P node will interact in order to execute and query the underlying implementation.
 *
 * The version of the OpenAPI document: x.x.x
 * Contact: support@ownera.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ownera.ledger.adapter.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.ownera.ledger.adapter.api.model.HashFunction;
import io.ownera.ledger.adapter.api.model.SignatureTemplate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.ownera.ledger.adapter.api.ApiClient;
/**
 * represent a signature template information
 */
@JsonPropertyOrder({
  Signature.JSON_PROPERTY_SIGNATURE,
  Signature.JSON_PROPERTY_TEMPLATE,
  Signature.JSON_PROPERTY_HASH_FUNC
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-23T11:29:49.092442+03:00[Asia/Jerusalem]", comments = "Generator version: 7.9.0")
public class Signature {
  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private String signature;

  public static final String JSON_PROPERTY_TEMPLATE = "template";
  private SignatureTemplate template;

  public static final String JSON_PROPERTY_HASH_FUNC = "hashFunc";
  private HashFunction hashFunc;

  public Signature() { 
  }

  public Signature signature(String signature) {
    this.signature = signature;
    return this;
  }

  /**
   * hex representation of the signature
   * @return signature
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(String signature) {
    this.signature = signature;
  }


  public Signature template(SignatureTemplate template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SignatureTemplate getTemplate() {
    return template;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplate(SignatureTemplate template) {
    this.template = template;
  }


  public Signature hashFunc(HashFunction hashFunc) {
    this.hashFunc = hashFunc;
    return this;
  }

  /**
   * Get hashFunc
   * @return hashFunc
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HASH_FUNC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public HashFunction getHashFunc() {
    return hashFunc;
  }


  @JsonProperty(JSON_PROPERTY_HASH_FUNC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHashFunc(HashFunction hashFunc) {
    this.hashFunc = hashFunc;
  }


  /**
   * Return true if this signature object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Signature signature = (Signature) o;
    return Objects.equals(this.signature, signature.signature) &&
        Objects.equals(this.template, signature.template) &&
        Objects.equals(this.hashFunc, signature.hashFunc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signature, template, hashFunc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Signature {\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    hashFunc: ").append(toIndentedString(hashFunc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `signature` to the URL query string
    if (getSignature() != null) {
      joiner.add(String.format("%ssignature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSignature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `template` to the URL query string
    if (getTemplate() != null) {
      joiner.add(getTemplate().toUrlQueryString(prefix + "template" + suffix));
    }

    // add `hashFunc` to the URL query string
    if (getHashFunc() != null) {
      joiner.add(String.format("%shashFunc%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getHashFunc()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

